name: Publish to NPM
on:
    push:
        branches:
            - 'main'
jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  registry-url: https://registry.npmjs.org/
                  node-version: '20'
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Publish package on NPM 📦
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
